{% set version = "0.1" %}

package:
  name: properscoring
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/properscoring/properscoring-{{ version }}.tar.gz
  sha256: b0cc4963cc218b728d6c5f77b3259c8f835ae00e32e82678cdf6936049b93961

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - scipy

test:
  requires:
    - python {{ python_min }}
  imports:
    - properscoring

about:
  home: https://github.com/TheClimateCorporation/properscoring
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Proper scoring rules in Python

extra:
  recipe-maintainers:
    - ocefpaf
