travis:
  secure:
    BINSTAR_TOKEN: rzCYQOLVr/aS4CcU+UY6+w5wfUxfPjR00Z+9zeSFll89fXFsgTP9Ec7Jgo1ROtnnFNcZlJM5WTfaCpvV125phi+lrZOe3TWufIlbNTp/fVBPX4whsEgTPgLUgNOYaxlvh0xF4Qbtatf0hbJs1GlAjW9tCg/bxXdflZi9bcJCkGLub+pOY7sGuzE8B4UreydOlkGUh7BQmYPTEv73KNLoRKsLfZ8avKQxiLg2UVjtp/LydqZdjK1pGJOe2p+S89SUqp5Pez/etbp/3XQSzf9sAcrKx6dQ+of84cj0SPVqGLSsaTT3Q6u3SGvXHcgDc+oejwf2rLfLr7ZPNdDdcHc7cz+NiHD4K+2vTizt6+cefIDlU6+llEykuaaD0J2Qj6yUMKfr3oqE1rcro7V6vqWt37O5260ERXVTcMKjeKmkn4hPCz+uJ1rTsQfHKNOQmXxLgG/BdNJ/xzOeGeQk5YPc+rJqs6twI8ZBRfzv7Yn/YfTUEzQ4mm3jtUIGkEe9R+cdviGgnadAMG5/VF0Q1JtNgCbwa3/1tl72/oYIidyfDoZg2A1LmmqfMhOeDQewabqOTctzkeCmnbskzXNSIUHVft9MoiJgp9RVTiXP0BtWAUrB2mQDVqJkzewhjnaCQ5xdpx2FRzdOErh18PLZ6OlDmMQRtE91R5Mi5/fy7niAVHQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
